### ISSUE TITLE
Rework economy and disposition

### ISSUE THREAD

**Issue by GalacticChimp** [Adeptus-Dominus/ChapterMaster#141]
Some ideas
- [ ] Rework dispotion so you don't need 100 dispo to actually do things
- [ ] Controlling at least 1 world with 80+ dispo should allow renegage Chapters to buy things
- [ ] Owning a hive or forge world means you can build ships, but with 1.5x the cost
- [ ] add another currency for heavy industrial works, like Stellaris?

**Comment by Blogaugis** [comment]
The way I understand equipment construction - the interstellar, warp-capable ships usually are so large and otherwise self-sustaining, that it is a fair guess that they'd have various workshops on board (This should be true for a battle barge for sure, whereas the smaller ships would be worthwhile of discussion - if we will see naval rework, of modifying ships and otherwise implementing components like 'on-board workshops', this could be another way for player to have a way to build as renegade.

Obviously, this also ties into the economy rework.
Rework of reworks, basically.

**Comment by GalacticChimp** [comment]
this got duplicated in #153, so closed that one
