### ISSUE TITLE
Add end game statistics

### ISSUE THREAD

**Issue by GalacticChimp** [Adeptus-Dominus/ChapterMaster#142]
Ideas:
- just add a i++ vars to show when your marines died, ship got destroyed etc.?
- might as well allow proper after-battle reports, changes between turns etc so that the Player can see his Chapter's ebb and flow throughout the years

**Comment by Blogaugis** [comment]
The very first one should be - how long the game lasted.

After that, here are a few ideas:

- Number of battles (Land and naval, separately) the player took part in;
- Top number of marines player had in the game;
- Total requisition spent;
- Number of ships player had (since they get a name generated for them, maybe have a list of them);
- Planets visited (how much of sector the player explored);
- STCs recovered;
- Ruins explored;
- Number of faction leaders defeated...

There can also be a few more debug-relevant values, like:

- Number of battles between AI factions (no player input);
- Number of events occurred;
- Number of extra-sector (or not) invasions (Waaaghs)...

After all, this end-game (maybe, it should be visible at any time in the game, not necessarily generated only at the end?) statistics screen is not only a way to perform debug-related analysis, but also bragging rights.
