### ISSUE TITLE
Rework PDF and IG into actual factions

### ISSUE THREAD

**Issue by GalacticChimp** [Adeptus-Dominus/ChapterMaster#144]
Currently PDF and IG are just a number, rework them into being actual factions, like Orcs, etc.

**Comment by Blogaugis** [comment]
I'm not sure about making PDF into separate faction.
They are effectively tied to the planets that they are on.
There might be some point to it if we want PDF to be movable (or build-able in) to different worlds, but that doesn't look like what standard loyalist factions would try to do. More a renegade/chaos play-through than a loyalist one.
Unless there are also plans to make each star system system (if not planet) be an inter-act-able diplomatic entity.

In terms of making them have a simple strength rating (rather than numbers) like other factions - yes.

**Comment by GalacticChimp** [comment]
> I'm not sure about making PDF into separate faction...

IMO at the very least they should have their own unit roster (even if it's a copy-pasted IG one + with some tweaks)
