### ISSUE TITLE
Sector generation

### ISSUE THREAD

**Issue by GalacticChimp** [Adeptus-Dominus/ChapterMaster#147]
TODO

improve sector generation

**Comment by Blogaugis** [comment]
Drawing inspiration from Dwarf Fortress (DF), Cataclysm: Bright Nights (CBN) (and some other games with world's procedural generation) there are some interesting options that perhaps could be implemented:

First would be - perhaps the sector generated can be, instead of generated anew each time, be reused? It is a bit like retiring a fortress in DF or creating a new character in the same world in CBN. Would it be possible for player to, after losing (or perhaps retiring) the chapter, try again with a different chapter in the same sector?

It also ties in to the chapter selection/creation screens - maybe first the sector has to be generated, and then the player chooses the chapter, starting location, how many (semi-)controlled planets the chapter has (like, an option whether You want several low quality planets (death/ice/desert world) or a single Hive world) and a few other nuances? Maybe a few options to edit the sector if there are several or few oddities in the generation?

Though, this would be a larger scale, rework of reworks, again...
