### ISSUE TITLE
Give Chaos some depth

### ISSUE THREAD

**Issue by GalacticChimp** [Adeptus-Dominus/ChapterMaster#150]
It's currently possible to play as Chaos/Renegade, however the experience is pretty shallow, basically a defeat lap. 

Find, design and implement ways to make Chaos Boys interesting and fun to play.

**Comment by Blogaugis** [comment]
It's a bit difficult issue to tackle as there are some fundamental questions needing answers:
Is the implementation going to be about possibility starting as chaos-aligned (or non-imperial) warband from the start?
Or is it going to be about improving the current adventure to renegade?

In the former's case, it's probably less issues about start - with the usual chaos warbands being badly mutated and otherwise unable to use the test-slave incubators - the go-to strategy would most likely be about controlling a fleet-based warband, raiding planets and evading stronger imperial patrols.
With a homeworld, it probably requires a scenario, where there are other chaos planets around you, distracting and otherwise buying time defending the place, while the imperial forces are on the offensive.
For a stealth option (such as infiltrating planets and inciting rebellions), we probably need to implement escorts being able to hide, and allow to sneakily deploy a squad or 2 of marines to pillage and cause other mischief.
We also going to need to add a way to hide the rest of forces, such as keeping the majority of your force hidden in a dead world system. Strategic psychic (with chaos+daemonic flavor) powers could also lend a hand.
Maybe that lair system could reworked into something more interesting, including movable bases.

While the path of advancing towards renegade "Victory" is more or less outlined in the 'Sector overlordship' discord discussion thread.
