### ISSUE TITLE
Rework save system basic functionality

### ISSUE THREAD

**Issue by GalacticChimp** [Adeptus-Dominus/ChapterMaster#171]
The current save system is less than ideal, here's a list of improvements:

- [X] investigate ways to make the save system more robust (currently you need to manually add each save and load step)
- [x] add save data structs and serialize() to each object which is supposed to be serializable
    - [x] obj_controller
    - [x] obj_ini
    - [x] global
    - [x] stars
    - [x] fleets
    - [x] misc
- [ ] make each save file totally independent
    - [ ] remove save list file
    - [ ] make sure each save file has all the data it needs to be totally independent
    - [X] move game options and settings to dedicated ini file
    - [ ] make saving the game actually clear the save file contents, instead of trying to update it
- [ ] add game version tracking to save files
    - [x] add game version to save file
    - [ ] check save files game version on entering save list screen
    - [ ] block from loading saves from invalid game versions
- [ ] add deserialize() to each object which is supposed to be serializable
    - [ ] obj_controller
    - [ ] obj_ini
    - [ ] global
    - [ ] stars
    - [ ] fleets
    - [ ] misc
- [ ] fix restart functionality
    - [ ] remove redundant restart variables (i.e. all of them)
    - [ ] use save data structs from serialize() instead
    - [ ] replace old restart scripts with logic shared with the save system
- [ ] make sure deleting saves still works properly
- [x] link save-load methods to save and load scripts
- [x] switch to json file format for unencrypted saves (.ini doesn't really support arrays of structs, which breaks marines' data)
- [ ] update UI
- [x] investigate save folder path options
- [x] set local game folder as settings and save folder path
- [x] remove screenshots for saved games
- [ ] implement error handling
    - [ ] at the very least, loading or saving a game should never crash or corrupt the current game.
    - [ ] if during loading, some data is not stored, then try to use default values, if it makes sense. Also log any such occurances.

Optional/tentative
- [ ] design mechanism which allows upgrading save file version in certain cases?
- [ ] try to generate a mini-map instead of screenshots, to abstractly represent game state of the save?

**Comment by Blogaugis** [comment]
Make saves take the same (sub)folder that the game is in (rather than documents).

**Comment by GalacticChimp** [comment]
> Make saves take the same (sub)folder that the game is in (rather than documents).

I've been thinking about this. Most games store saves in documents folder and it seems to work fine enough? The issues we have with saves sometimes getting corupted is caused by 3 elements: 

- improper versioning of save files, 
- redundant save files list 
- improper updating of already existing saves

Once these 3 are fixed, then players won't have to delete old save/app files after each release.

**Comment by Blogaugis** [comment]
> Most games store saves in documents folder and it seems to work fine enough?

Kind of, but, how similar CM is to 'most games'? It is a niche one, something similar to dwarf fortress, and I've seen it storing saves in the same (sub)folder it is in.
Firstly, this makes sure that the space for saves is used in the same partition (same disc drive) as the game itself. And while it may not be much of an issue by itself, some folks prefer to have discs/partitions dedicated to games, while keeping others reserved for other things.
But, personal preferences aside, and more game-focused reasons:

- **Save-editing**. It would be easier to engage in save-editing/repair/etc, by not having to navigate to appdata folder (W10 by default hides this folder, meaning that low-end user/player won't be able to actually reach the saves, and, worse, **settings**).
- **Soft-locking.** Not being able to reach (basically delete, when a new update comes out) settings, may end up soft-locking low-end users/players. They are stuck to using old settings file, while the game itself is so new... Needless to say, this is the place where we, in one case, would be getting plenty of false-positive bugs... Most likely, however, would be that low-end players would simply drop this game right here and go play something else...
- **Bughunting.** Since the game is still very early in development, bugs will be present. And one way to find the issues is by giving the players the option to send the saves. However, low end user won't be able to send save files, if he/she can't get there.

Obviously, this settings file keeping (and saves) can be left, but then the game should automatically delete the old (or new, if the player wants to play older version) settings file upon launch, if it finds a version mismatch. It would complicate some bug finding, but at least the game would still be playable.

Still, if saves (and settings) are going to be present in the documents folder rather than the (hidden by default) appdata folder, this would be an improvement. Not ideal for me personally, but still acceptable.
